openapi: 3.0.0
info:
  title: Notion Page Fetch
  version: 1.0.0
paths:
  /v1/pages/{page_id}:
    get:
      summary: Get a Notion page by ID
      parameters:
        - name: page_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A Notion page
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
